//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onigaku
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MLS_DBEntities1 : DbContext
    {
        public static MLS_DBEntities1 context;
        public MLS_DBEntities1()
            : base("MLS_DBEntities1")
        {
        }
        public static MLS_DBEntities1 GetContext()
        {
            if (context == null)
                context = new MLS_DBEntities1();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access> accesses { get; set; }
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<coverart> coverarts { get; set; }
        public virtual DbSet<performer> performers { get; set; }
        public virtual DbSet<playlist> playlists { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<tracks_info> tracks_info { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
