//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onigaku
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int rating_id { get; set; }
        public Nullable<decimal> mark { get; set; }
        public Nullable<int> track_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual tracks_info tracks_info { get; set; }
    }
}
