//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onigaku
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tracks()
        {
            this.playlists = new HashSet<playlists>();
        }
    
        public int track_id { get; set; }
        public Nullable<int> performer_id { get; set; }
        public Nullable<int> track_duration { get; set; }
        public string genre { get; set; }
        public Nullable<int> bitrate { get; set; }
    
        public virtual performers performers { get; set; }
        public virtual tracks_info tracks_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlists> playlists { get; set; }
    }
}
