//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onigaku
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracks_playlist
    {
        public int playlist_id { get; set; }
        public int user_id { get; set; }
        public int track_id { get; set; }
        public string track_name { get; set; }
        public string playlist_name { get; set; }
    }
}
